molecules = {
  -- Existing molecules
  ["H₂O"] = {color = "blue", name = "Water"},
  ["CO₂"] = {color = "gray", name = "Carbon Dioxide"},
  ["CH₄"] = {color = "neonblue", name = "Methane"},
  ["O₂"] = {color = "red", name = "Oxygen"},
  ["N₂"] = {color = "violet", name = "Nitrogen"},
  ["H₂"] = {color = "yellow", name = "Hydrogen"},
  ["C₆H₁₂O₆"] = {color = "green", name = "Glucose"},
  ["C₂H₅OH"] = {color = "darkblue", name = "Ethanol"},
  ["NH₃"] = {color = "gray", name = "Ammonia"},
  ["C₈H₁₀N₄O₂"] = {color = "neonblue", name = "Caffeine"},
  ["C₃H₈"] = {color = "red", name = "Propane"},
  ["C₁₀H₈"] = {color = "violet", name = "Naphthalene"},
  ["C₅H₅N₅O"] = {color = "yellow", name = "Theobromine"},
  ["C₂H₆"] = {color = "green", name = "Ethane"},
  ["C₃H₆O"] = {color = "darkblue", name = "Acetone"},
  ["C₄H₁₀"] = {color = "gray", name = "Butane"},
  ["C₆H₆"] = {color = "neonblue", name = "Benzene"},
  ["C₇H₈"] = {color = "red", name = "Toluene"},
  ["C₇H₆N₂O₄S"] = {color = "violet", name = "Aspirin"},
  
  -- Additional molecules
  ["C₅H₁₂"] = {color = "blue", name = "Pentane"},
  ["C₄H₁₀O"] = {color = "gray", name = "Butanol"},
  ["C₈H₁₈"] = {color = "neonblue", name = "Octane"},
  ["C₉H₂₀"] = {color = "red", name = "Nonane"},
  ["C₁₀H₂₂"] = {color = "violet", name = "Decane"},
  ["C₇H₁₆"] = {color = "yellow", name = "Heptane"},
  ["C₆H₁₄"] = {color = "green", name = "Hexane"},
  ["C₅H₁₀O"] = {color = "darkblue", name = "Pentanol"},
  ["C₄H₈O"] = {color = "gray", name = "Butanone"},
  ["C₆H₁₀O"] = {color = "neonblue", name = "Hexanone"},
  ["C₅H₁₀"] = {color = "red", name = "Pentene"},
  ["C₄H₈"] = {color = "violet", name = "Butene"},
  ["C₆H₁₂"] = {color = "yellow", name = "Cyclohexane"},
  ["C₅H₁₀N₂O₂"] = {color = "green", name = "Urea"},
  ["C₄H₇NO₂"] = {color = "darkblue", name = "Proline"},
  ["C₆H₁₂O₃"] = {color = "gray", name = "Citric Acid"},
  ["C₅H₈O₂"] = {color = "neonblue", name = "Acetic Acid"},
  ["C₇H₄O₂"] = {color = "red", name = "Benzoic Acid"},
  ["C₆H₆O₃"] = {color = "violet", name = "Salicylic Acid"},
  ["C₄H₈O₃"] = {color = "yellow", name = "Acetylsalicylic Acid"},
  -- Add more molecules and their colors and names as needed
}

