ATOM_DEFS = {
    {"Hydrogen", "H", "gray"},
    {"Helium", "He", "neonblue"},
    {"Lithium", "Li", "red"},
    {"Beryllium", "Be", "gray"},
    {"Boron", "B", "darkblue"},
    {"Carbon", "C", "darkblue"},
    {"Nitrogen", "N", "darkblue"},
    {"Oxygen", "O", "darkblue"},
    {"Fluorine", "F", "green"},
    {"Neon", "Ne", "neonblue"},
    {"Sodium", "Na", "red"},
    {"Magnesium", "Mg", "gray"},
    {"Aluminum", "Al", "gray"},
    {"Silicon", "Si", "darkblue"},
    {"Phosphorus", "P", "darkblue"},
    {"Sulfur", "S", "yellow"},
    {"Chlorine", "Cl", "green"},
    {"Argon", "Ar", "neonblue"},
    {"Potassium", "K", "red"},
    {"Calcium", "Ca", "gray"},
    {"Scandium", "Sc", "gray"},
    {"Titanium", "Ti", "gray"},
    {"Vanadium", "V", "gray"},
    {"Chromium", "Cr", "gray"},
    {"Manganese", "Mn", "gray"},
    {"Iron", "Fe", "gray"},
    {"Cobalt", "Co", "gray"},
    {"Nickel", "Ni", "gray"},
    {"Copper", "Cu", "gray"},
    {"Zinc", "Zn", "gray"},
    {"Gallium", "Ga", "gray"},
    {"Germanium", "Ge", "darkblue"},
    {"Arsenic", "As", "darkblue"},
    {"Selenium", "Se", "yellow"},
    {"Bromine", "Br", "red"},
    {"Krypton", "Kr", "neonblue"},
    {"Rubidium", "Rb", "red"},
    {"Strontium", "Sr", "gray"},
    {"Yttrium", "Y", "gray"},
    {"Zirconium", "Zr", "gray"},
    {"Niobium", "Nb", "gray"},
    {"Molybdenum", "Mo", "gray"},
    {"Technetium", "Tc", "gray"},
    {"Ruthenium", "Ru", "gray"},
    {"Rhodium", "Rh", "gray"},
    {"Palladium", "Pd", "gray"},
    {"Silver", "Ag", "gray"},
    {"Cadmium", "Cd", "gray"},
    {"Indium", "In", "gray"},
    {"Tin", "Sn", "gray"},
    {"Antimony", "Sb", "darkblue"},
    {"Tellurium", "Te", "darkblue"},
    {"Iodine", "I", "violet"},
    {"Xenon", "Xe", "neonblue"},
    {"Cesium", "Cs", "red"},
    {"Barium", "Ba", "gray"},
    {"Lanthanum", "La", "gray"},
    {"Cerium", "Ce", "gray"},
    {"Praseodymium", "Pr", "gray"},
    {"Neodymium", "Nd", "gray"},
    {"Promethium", "Pm", "gray"},
    {"Samarium", "Sm", "gray"},
    {"Europium", "Eu", "gray"},
    {"Gadolinium", "Gd", "gray"},
    {"Terbium", "Tb", "gray"},
    {"Dysprosium", "Dy", "gray"},
    {"Holmium", "Ho", "gray"},
    {"Erbium", "Er", "gray"},
    {"Thulium", "Tm", "gray"},
    {"Ytterbium", "Yb", "gray"},
    {"Lutetium", "Lu", "gray"},
    {"Hafnium", "Hf", "gray"},
    {"Tantalum", "Ta", "gray"},
    {"Tungsten", "W", "gray"},
    {"Rhenium", "Re", "gray"},
    {"Osmium", "Os", "gray"},
    {"Iridium", "Ir", "gray"},
    {"Platinum", "Pt", "gray"},
    {"Gold", "Au", "yellow"},
    {"Mercury", "Hg", "gray"},
    {"Thallium", "Tl", "gray"},
    {"Lead", "Pb", "gray"},
    {"Bismuth", "Bi", "gray"},
    {"Polonium", "Po", "gray"},
    {"Astatine", "At", "violet"},
    {"Radon", "Rn", "neonblue"},
    {"Francium", "Fr", "red"},
    {"Radium", "Ra", "gray"},
    {"Actinium", "Ac", "gray"},
    {"Thorium", "Th", "gray"},
    {"Protactinium", "Pa", "gray"},
    {"Uranium", "U", "gray"},
    {"Neptunium", "Np", "gray"},
    {"Plutonium", "Pu", "gray"},
    {"Americium", "Am", "gray"},
    {"Curium", "Cm", "gray"},
    {"Berkelium", "Bk", "gray"},
    {"Californium", "Cf", "gray"},
    {"Einsteinium", "Es", "gray"},
    {"Fermium", "Fm", "gray"},
    {"Mendelevium", "Md", "gray"},
    {"Nobelium", "No", "gray"},
    {"Lawrencium", "Lr", "gray"},
    {"Rutherfordium", "Rf", "gray"},
    {"Dubnium", "Db", "gray"},
    {"Seaborgium", "Sg", "gray"},
    {"Bohrium", "Bh", "gray"},
    {"Hassium", "Hs", "gray"},
    {"Meitnerium", "Mt", "gray"},
    {"Darmstadtium", "Ds", "gray"},
    {"Roentgenium", "Rg", "gray"},
    {"Copernicium", "Cn", "gray"},
    {"Nihonium", "Nh", "gray"},
    {"Flerovium", "Fl", "gray"},
    {"Moscovium", "Mc", "gray"},
    {"Livermorium", "Lv", "gray"},
    {"Tennessine", "Ts", "gray"},
    {"Oganesson", "Og", "gray"}
}

LEVEL_DEFS = {
    ['easy'] = {
        {
            yGravity = 10,
            
        }
    }
}

ITEM_DEFS = {
    ['Auto-Complete'] = {
        description = 'This power-up automatically fills in the next few letters of the word for the player, allowing them to type more quickly.'

    },
    ['Bonus Points'] = {
        description = 'Grants additional points for each correctly typed word while the power-up is active'
    },
    ['Invincibility'] = {
        description = 'Makes the player immune to typing errors and penalties for a limited time, allowing them to make mistakes without consequences for a short period of time.',
        --the time will depend on upgrading this as well as other items
    },
    ['Word Eraser'] = {
        description = 'Allows the player to eliminate a molecule to make'
    },
    ['Multiplier'] = {
        description = 'Multiplies the point value of each correctly typed word for a set duration.'
    },
    ['Combo Extender'] = {
        description = 'Can be used to extend the typing streak'
    }
}

MOLECULE_DEFS = {

    -- Existing molecules
    ["H₂O"] = {color = "blue", name = "Water"},
    ["CO₂"] = {color = "gray", name = "Carbon Dioxide"},
    ["CH₄"] = {color = "neonblue", name = "Methane"},
    ["O₂"] = {color = "red", name = "Oxygen"},
    ["N₂"] = {color = "violet", name = "Nitrogen"},
    ["H₂"] = {color = "yellow", name = "Hydrogen"},
    ["C₆H₁₂O₆"] = {color = "green", name = "Glucose"},
    ["C₂H₅OH"] = {color = "darkblue", name = "Ethanol"},
    ["NH₃"] = {color = "gray", name = "Ammonia"},
    ["C₈H₁₀N₄O₂"] = {color = "neonblue", name = "Caffeine"},
    ["C₃H₈"] = {color = "red", name = "Propane"},
    ["C₁₀H₈"] = {color = "violet", name = "Naphthalene"},
    ["C₅H₅N₅O"] = {color = "yellow", name = "Theobromine"},
    ["C₂H₆"] = {color = "green", name = "Ethane"},
    ["C₃H₆O"] = {color = "darkblue", name = "Acetone"},
    ["C₄H₁₀"] = {color = "gray", name = "Butane"},
    ["C₆H₆"] = {color = "neonblue", name = "Benzene"},
    ["C₇H₈"] = {color = "red", name = "Toluene"},
    ["C₇H₆N₂O₄S"] = {color = "violet", name = "Aspirin"},
    
    -- Additional molecules
    ["C₅H₁₂"] = {color = "blue", name = "Pentane"},
    ["C₄H₁₀O"] = {color = "gray", name = "Butanol"},
    ["C₈H₁₈"] = {color = "neonblue", name = "Octane"},
    ["C₉H₂₀"] = {color = "red", name = "Nonane"},
    ["C₁₀H₂₂"] = {color = "violet", name = "Decane"},
    ["C₇H₁₆"] = {color = "yellow", name = "Heptane"},
    ["C₆H₁₄"] = {color = "green", name = "Hexane"},
    ["C₅H₁₀O"] = {color = "darkblue", name = "Pentanol"},
    ["C₄H₈O"] = {color = "gray", name = "Butanone"},
    ["C₆H₁₀O"] = {color = "neonblue", name = "Hexanone"},
    ["C₅H₁₀"] = {color = "red", name = "Pentene"},
    ["C₄H₈"] = {color = "violet", name = "Butene"},
    ["C₆H₁₂"] = {color = "yellow", name = "Cyclohexane"},
    ["C₅H₁₀N₂O₂"] = {color = "green", name = "Urea"},
    ["C₄H₇NO₂"] = {color = "darkblue", name = "Proline"},
    ["C₆H₁₂O₃"] = {color = "gray", name = "Citric Acid"},
    ["C₅H₈O₂"] = {color = "neonblue", name = "Acetic Acid"},
    ["C₇H₄O₂"] = {color = "red", name = "Benzoic Acid"},
    ["C₆H₆O₃"] = {color = "violet", name = "Salicylic Acid"},
    ["C₄H₈O₃"] = {color = "yellow", name = "Acetylsalicylic Acid"},
    -- Add more molecules and their colors and names as needed
  }
  
  